### ISSUE TITLE
Root access only 

### ISSUE THREAD

**Issue by ghost** [khoivan88/open_enventory-for-MIT#12]
Good day,
I've just installed Open Enventory on Centos according to manual.
Everything is ok, except one thing: i able to login lab web interface only under root.
I tried to create another users in phpmyadmin, and assign them to several different databases, but in vain.
Is it possible to fix it?
Or access to Open Enventory is only available under root account?

**Comment by thomiczecks** [comment]
Hi @glenryar,
you have to create the users inside OpenEnventory itself because the systems needs to generate some default values for the database which phpmyadmin is not able to do. 
To do this login as root and follow the guide @khoivan88 has created.
https://open-enventory.gitbook.io/user-guides/user-guides/chemical-inventory/users/create-a-new-user

**Comment by ghost** [comment]
@thomiczecks got it, thank you very much.
