### ISSUE TITLE
safety data sheet download

### ISSUE THREAD

**Issue by thomiczecks** [khoivan88/open_enventory-for-MIT#8]
Hey,
I know you're not the original author of open enventory but maybe you or somebody else can help. I'm trying to set up open enventory for my working group and it runs fine except for the automatic safety sheet download. Every other part of the supplier scraping works fine. Is it working for you? Does it require any special package?
I'm running it on Ubuntu-18.04, nginx-1.14.0, mysql-15.1, php-7.1.33.

thanks in advance,
thomiczecks

**Comment by khoivan88** [comment]
Hi thomiczecks,

No problem. I will try my best to help you any way I can and if it is not
possible, we can ask Felix (Open Enventory author) in riot chatroom too. I
know he is active in there.

Ok, to your problem, a couple questions:
1. Does your server based in the US or Europe, I know that the original OE
code is Europe base so not modifying those supplier scraping tools can
present you with problem. The servers I set up all base in the US so I know
I had to modify Sigma Aldrich, VWR, Fisher. Knowing the answer to this, we
can twitch some of the supplier files to see if it helps.
2. Even with twitching the suppliers scraping tool, I know that I usually
got about 50-80% of the SDS file with all of the chemicals having CAS#. My
question is do you see some chemicals with good SDS and some without or
none of your chemicals have SDS?
3. Does the automatic SDS download fail in "Import from tab-separated text
file" or in "Batch Processing" or in Manual find SDS function for each
chemicals?
Question 2 and 3 are kinda interrelated but it could help me a bit in
trying to find your SDS files.

If all attempts are failed, I did write some python script to scrape those
missing SDS files. I think it increases to about 90% of all chemicals with
CAS having SDS.

I am happy to help so please don't hesitate to ask any questions.

Best regards,

Khoi

**Comment by thomiczecks** [comment]
thanks for the fast response. I already had a brief email exchange with Felix and according to him it should work without a problem :D.

1. the server is based in Europe. But I have 2 instances running: one with your version and one with the original version from sourceforge and both are failing although I see the differences in the other data scraping (name, boiling points, etc.)
2. at the moment i have a limited data set but for what i see i didn't get any file. Except for some Acros .html which are without content. Maybe all my entrys belong to the failing 50% :D.
3. well technically the download does not fail (at least I'm not seeing any warning/error), but it doesn't matter wether I'm inputting them manually or automatically with the input or batch processing

If you could give me a working CAS# I could try wether it's only my data set that is bad.

Thanks,
thomiczecks

**Comment by khoivan88** [comment]
Hi thomiczecks,

Since you have tested both Felix and my code, I think we can rule out that.
Since your server based in Europe, Felix version might work a bit better. I
put together a quick file that I believe that with the Import text
function, OE should be able to find SDS file. Could you please import the
attached file and let me know if OE imported SDS correctly? It is properly
best to test on a brand new database so that already imported database does
not skew the result (you might already know that so I apologize in advance)
[chemical_for_sds.txt](https://github.com/khoivan88/open_enventory-modified_for_US/files/4037647/chemical_for_sds.txt)

In any case, I might not have a long term solution for you (which is fixing
the OE code because this issue was not too problematic for me). However, we
can try the python script I wrote to see if it might help.
Let me know the result of the import file.
Khoi

Name	CAS
benzene-d6	1076-43-3
Chloramine T trihydrate	7080-50-4
Zinc acetate dihydrate	5970-45-6
Methenamine	100-97-0
Magnesium perchlorate	10034-81-8

**Comment by thomiczecks** [comment]
Hi Khoi,
so the import worked fine on both instances and i got similar results (missing structure on chloramine) but I'm only getting SDS for Zinc acetate dihydrate and Magnesium perchlorate.

**Comment by khoivan88** [comment]
Hi thomiczecks,

I was expecting CarlRoth for the other 3 chemicals as well. (see picture for my database with SDS). 
![Annotation 2020-01-08 175919](https://user-images.githubusercontent.com/33493502/72023519-05376180-3241-11ea-8640-34efbc1aa6b5.png)
![Annotation 2020-01-08 175948](https://user-images.githubusercontent.com/33493502/72023521-05376180-3241-11ea-8736-0d8122cf4b81.png)


Anyway, because I am such a novice in PHP, I don't have the long term solution for you yet. However, I can offer you what I did for my database, this github is my python code for finding missing SDS for OE (I have one for finding missing structure as well as finding missing safety info such as warning and safety code. Let me know if you want them as well)
Github: https://github.com/khoivan88/find_missing_sds-public
This script basically looks into your OE database of interest, find the molecule (CAS#) with missing structure or SDS and then proceed to scrape from the internet for that info. You would need python on your hosting server and root (on the host server) access. Are you familiar with python? if so, you can:
1. clone the repo
2. Switch to root user with `su`
2. (Optional) create the virtual environment
3. Go to the repo folder and install the pip dependency with `cd find_missing_sds-public && pip install -r requirements.txt`
4. Go into the folder of the python file: `cd find_missing_sds_v5`
5. Run the python file with: `python find_missing_sds.py` and follow the direction: type in root password, type the name of the database x 2 and wait

If you are not familiar with python, please let me know and I can give more detailed instruction.

**Comment by khoivan88** [comment]
I forgot to tell you that the python script above is intended to be run after you have imported chemicals into your database. You have to run it manually (which means OE does not trigger the python script to run) whenever you want to update your database info. Of course, you could also hardcode the mysql root password (or safer to use environmental variable) and then use crontab to run the script periodically as well. 
I hope the script help your database. I don't think the script has been run from Europe so I'm curious about the result.

**Comment by thomiczecks** [comment]
it worked like a charm. Thanks a lot. Every SDS is now available. I'll have a look into the original supplier scraping when I get my testing enviroment set up because according to Felix, sites like CarlRoth should still work since they use hardcoded urls. Only sites like Sigma are deprecated since they are using a more complex cookie based system for SDS download which he only implemented in the sciformation ELN.
Thanks again for your help and work,
thomiczecks

**Comment by khoivan88** [comment]
Hi thomiczecks,
That is awesome to hear. I agree that sites like Sigma are notoriously hard to scrape. Even with my python code, Sigma was not one of the sources. Unfortunately, web scraping in PHP is way above my head so I can't really fix OE on that. Of course, I could put in a code for the PHP to trigger my python code running (during "Batch processing", for example) but that is not a very elegant fix, lol. 
About my python code, it downloads the PDF files of SDS into `/var/lib/mysql/missing_sds` so if you need disk space, you can delete that folder. I did not do a cleanup code for that because my workflow is to run the python script periodically and the script will check to make sure that that folder does not contain the PDF file already before downloading. Now talking about that, a cleanup code for that folder might be in order. 
Anyway, I am glad it worked well for you. If you fix the OE original PHP, I would love to hear about it.
Khoi
